/**
 * OpenWeatherMap API
 * Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.
 *
 * OpenAPI spec version: 2.5
 * Contact: some_email@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenWeatherMapApi) {
      root.OpenWeatherMapApi = {};
    }
    root.OpenWeatherMapApi.Main = factory(root.OpenWeatherMapApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Main model module.
   * @module model/Main
   * @version 2.5
   */

  /**
   * Constructs a new <code>Main</code>.
   * @alias module:model/Main
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Main</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Main} obj Optional instance to populate.
   * @return {module:model/Main} The populated <code>Main</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('grnd_level')) {
        obj['grnd_level'] = ApiClient.convertToType(data['grnd_level'], 'Number');
      }
      if (data.hasOwnProperty('humidity')) {
        obj['humidity'] = ApiClient.convertToType(data['humidity'], 'Number');
      }
      if (data.hasOwnProperty('pressure')) {
        obj['pressure'] = ApiClient.convertToType(data['pressure'], 'Number');
      }
      if (data.hasOwnProperty('sea_level')) {
        obj['sea_level'] = ApiClient.convertToType(data['sea_level'], 'Number');
      }
      if (data.hasOwnProperty('temp')) {
        obj['temp'] = ApiClient.convertToType(data['temp'], 'Number');
      }
      if (data.hasOwnProperty('temp_max')) {
        obj['temp_max'] = ApiClient.convertToType(data['temp_max'], 'Number');
      }
      if (data.hasOwnProperty('temp_min')) {
        obj['temp_min'] = ApiClient.convertToType(data['temp_min'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Atmospheric pressure on the ground level, hPa
   * @member {Number} grnd_level
   */
  exports.prototype['grnd_level'] = undefined;
  /**
   * Humidity, %
   * @member {Number} humidity
   */
  exports.prototype['humidity'] = undefined;
  /**
   * Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa
   * @member {Number} pressure
   */
  exports.prototype['pressure'] = undefined;
  /**
   * Atmospheric pressure on the sea level, hPa
   * @member {Number} sea_level
   */
  exports.prototype['sea_level'] = undefined;
  /**
   * Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
   * @member {Number} temp
   */
  exports.prototype['temp'] = undefined;
  /**
   * Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
   * @member {Number} temp_max
   */
  exports.prototype['temp_max'] = undefined;
  /**
   * Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.
   * @member {Number} temp_min
   */
  exports.prototype['temp_min'] = undefined;



  return exports;
}));


